### ISSUE TITLE
Missing Language strings

### ISSUE THREAD

**Issue by agrowe** [jl2035/moodle_mod_mootyper#22]
Hi, It looks like there are permissions defined in access.php that do not have corresponding language strings. The ones I get errors for are

```
$string['mootyper:editall'] = '';
$string['mootyper:aftersetup'] = '';
$string['mootyper:setup'] = '';
$string['mootyper:view'] = '';
$string['mootyper:viewgrades'] = '';
```

Thanks
Alex

**Comment by drachels** [comment]
I have a fix and would like to take over and start maintaining MooTyper.

**Comment by jl2035** [comment]
Glad to hear that. Do you want to create a pull request or do I just add you as a project collaborator?

**Comment by drachels** [comment]
I'm not sure which would be better at the moment, but probably collaborator. I'm mainly just wanting to be able to get updated versions of MooTyper online at Moodle so that there are versions for Moodle 2.8, 2.9, 3.0 and the upcoming 3.1. I would also like to try and add some new stuff such as backup. Eventually, I would like to try and make a convenient way of importing and exporting lessons.

**Comment by jl2035** [comment]
I have added you here and on moodle.org as a maintainer. We'll be in touch.

**Comment by drachels** [comment]
Thanks. I'm currently working on a version for Moodle 2.9 and adding classes/events for the new log system.

**Comment by drachels** [comment]
Added five missing language strings for Permissions to master.
$string['mootyper:aftersetup'] = 'After setup';
$string['mootyper:setup'] = 'Setup';
$string['mootyper:view'] = 'View';
$string['mootyper:viewgrades'] = 'View all grades';
$string['mootyper:viewmygrades'] = 'View my grades';

**Comment by drachels** [comment]
I also added an invalid access string.
